# Generated by Django 4.1.1 on 2022-10-31 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='estado_respuesta',
            field=models.CharField(blank=True, choices=[('Contestada', 'Contestada'), ('No Contestada', 'No Contestada'), ('En proceso', 'En proceso')], default='No Contestada', max_length=15, null=True),
        ),
    ]
