# Generated by Django 4.1.1 on 2022-10-19 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datosusuario',
            name='cuit',
        ),
        migrations.RemoveField(
            model_name='datosusuario',
            name='documento',
        ),
        migrations.RemoveField(
            model_name='datosusuario',
            name='fecha_nacimiento',
        ),
        migrations.RemoveField(
            model_name='datosusuario',
            name='telefono',
        ),
        migrations.AddField(
            model_name='datosusuario',
            name='dni',
            field=models.IntegerField(blank=True, default=1111111),
        ),
        migrations.AddField(
            model_name='datosusuario',
            name='nro_animales',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='datosusuario',
            name='celular',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='datosusuario',
            name='codigo_postal',
            field=models.IntegerField(blank=True),
        ),
    ]
