# Generated by Django 3.2.5 on 2022-09-12 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_auto_20220911_2318'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='descripcion',
            field=models.CharField(db_index=True, default='descripcion', max_length=250),
        ),
    ]
