# Generated by Django 4.1.3 on 2023-02-27 20:37

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_producto_accesorios'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='contenido',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='contenido'),
        ),
    ]
