# Generated by Django 4.1.3 on 2023-02-27 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_producto_contenido'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='contenido',
        ),
    ]
