# Generated by Django 4.1.3 on 2023-02-27 21:05

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0005_historicalproducto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproducto',
            name='descripcion',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='descripcion'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='descripcion'),
        ),
    ]
